/*
 * Copyright 2019 Miroslav Pokorny (github.com/mP1)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package walkingkooka.j2cl.maven;

import com.google.javascript.jscomp.CompilationLevel;
import com.google.javascript.jscomp.CompilerOptions.LanguageMode;
import walkingkooka.collect.list.Lists;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.function.Predicate;

/**
 * A {@link J2clRequest} that accompanies a test. The entry points and initial-script-filename are NOT taken from the pom,
 * but rather generated by {@link J2clMojoTest} and this request is reused over multiple tests.
 */
final class J2clMojoTestRequest extends J2clRequest {

    static J2clMojoTestRequest with(final J2clPath base,
                                    final J2clPath target,
                                    final J2clClasspathScope scope,
                                    final Map<J2clArtifactCoords, List<J2clArtifactCoords>> addedDependencies,
                                    final List<J2clArtifactCoords> classpathRequired,
                                    final List<J2clArtifactCoords> ignored,
                                    final List<J2clArtifactCoords> javascriptSourceRequired,
                                    final Map<J2clArtifactCoords, J2clArtifactCoords> replaced,
                                    final CompilationLevel level,
                                    final Map<String, String> defines,
                                    final Set<String> externs,
                                    final Set<ClosureFormattingOption> formatting,
                                    final LanguageMode languageOut,
                                    final List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers,
                                    final String testClassName,
                                    final int testTimeout,
                                    final J2clMavenMiddleware middleware,
                                    final ExecutorService executor,
                                    final J2clLogger logger) {
        return new J2clMojoTestRequest(base,
                target,
                scope,
                addedDependencies,
                classpathRequired,
                ignored,
                javascriptSourceRequired,
                replaced,
                level,
                defines,
                externs,
                formatting,
                languageOut,
                browsers,
                testClassName,
                testTimeout,
                middleware,
                executor,
                logger);
    }

    private J2clMojoTestRequest(final J2clPath base,
                                final J2clPath target,
                                final J2clClasspathScope scope,
                                final Map<J2clArtifactCoords, List<J2clArtifactCoords>> addedDependencies,
                                final List<J2clArtifactCoords> classpathRequired,
                                final List<J2clArtifactCoords> ignored,
                                final List<J2clArtifactCoords> javascriptSourceRequired,
                                final Map<J2clArtifactCoords, J2clArtifactCoords> replaced,
                                final CompilationLevel level,
                                final Map<String, String> defines,
                                final Set<String> externs,
                                final Set<ClosureFormattingOption> formatting,
                                final LanguageMode languageOut,
                                final List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers,
                                final String testClassName,
                                final int testTimeout,
                                final J2clMavenMiddleware middleware,
                                final ExecutorService executor,
                                final J2clLogger logger) {
        super(base,
                target,
                scope,
                addedDependencies,
                classpathRequired,
                ignored,
                javascriptSourceRequired,
                replaced,
                level,
                defines,
                externs,
                formatting,
                languageOut,
                middleware,
                executor,
                logger);
        this.browsers = browsers;
        this.testClassName = testClassName;
        this.testTimeout = testTimeout;
    }

    @Override
    J2clSourcesKind sourcesKind() {
        return J2clSourcesKind.TEST;
    }

    @Override
    List<String> entryPoints() {
        // this is the mangled name of a javascript file produced by the junit annotation-processor.
        return Lists.of("javatests." + this.testClassName + "_AdapterSuite");
    }

    @Override
    J2clPath initialScriptFilename() {
        return this.project.directory()
                .append(J2clStep.CLOSURE_COMPILER.directoryName())
                .output()
                .append(this.testClassName + ".js");
    }

    @Override
    String hash() {
        if (null == this.hash) {
            final HashBuilder hash = this.computeHash();
            // no need to include browser or testTimeout in hash as these do no affect generated js
            hash.append(this.testClassName);
            this.hash = hash.toString();
        }
        return this.hash;
    }

    /**
     * Lazily computed and cached hash.
     */
    private String hash;

    J2clMojoTestRequest setProject(final J2clDependency project) {
        this.project = project;

        return this;
    }

    private J2clDependency project;

    @Override
    List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers() {
        return this.browsers;
    }

    private final List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers;

    private final String testClassName;

    @Override
    int testTimeout() {
        return this.testTimeout;
    }

    int testTimeout;
}
