/*
 * Copyright 2019 Miroslav Pokorny (github.com/mP1)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package walkingkooka.j2cl.maven;

import com.google.javascript.jscomp.CompilationLevel;
import com.google.javascript.jscomp.CompilerOptions.LanguageMode;
import walkingkooka.collect.list.Lists;
import walkingkooka.j2cl.maven.closure.ClosureFormattingOption;
import walkingkooka.j2cl.maven.hash.HashBuilder;
import walkingkooka.j2cl.maven.log.BrowserLogLevel;
import walkingkooka.j2cl.maven.log.MavenLogger;
import walkingkooka.j2cl.maven.test.J2clStepWorkerWebDriverUnitTestRunnerBrowser;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * A {@link J2clMavenContext} that accompanies a test. The entry points and initial-script-filename are NOT taken from the pom,
 * but rather generated by {@link J2clMojoTest} and this {@link J2clMavenContext} is reused over multiple tests.
 */
public final class J2clMojoTestMavenContext extends J2clMavenContext {

    static J2clMojoTestMavenContext with(final J2clPath cache,
                                         final J2clPath target,
                                         final J2clClasspathScope scope,
                                         final List<J2clArtifactCoords> classpathRequired,
                                         final List<J2clArtifactCoords> ignoredDependencies,
                                         final List<J2clArtifactCoords> javascriptSourceRequired,
                                         final CompilationLevel level,
                                         final Map<String, String> defines,
                                         final Set<String> externs,
                                         final Set<ClosureFormattingOption> formatting,
                                         final Set<String> javaCompilerArguments,
                                         final LanguageMode languageOut,
                                         final Optional<String> sourceMaps,
                                         final List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers,
                                         final BrowserLogLevel browserLogLevel,
                                         final String testClassName,
                                         final int testTimeout,
                                         final J2clMavenMiddleware middleware,
                                         final int threadPoolSize,
                                         final MavenLogger logger) {
        return new J2clMojoTestMavenContext(
                cache,
                target,
                scope,
                classpathRequired,
                ignoredDependencies,
                javascriptSourceRequired,
                level,
                defines,
                externs,
                formatting,
                javaCompilerArguments,
                languageOut,
                sourceMaps,
                browsers,
                browserLogLevel,
                testClassName,
                testTimeout,
                middleware,
                threadPoolSize,
                logger
        );
    }

    private J2clMojoTestMavenContext(final J2clPath cache,
                                     final J2clPath target,
                                     final J2clClasspathScope scope,
                                     final List<J2clArtifactCoords> classpathRequired,
                                     final List<J2clArtifactCoords> ignoredDependencies,
                                     final List<J2clArtifactCoords> javascriptSourceRequired,
                                     final CompilationLevel level,
                                     final Map<String, String> defines,
                                     final Set<String> externs,
                                     final Set<ClosureFormattingOption> formatting,
                                     final Set<String> javaCompilerArguments,
                                     final LanguageMode languageOut,
                                     final Optional<String> sourceMaps,
                                     final List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers,
                                     final BrowserLogLevel browserLogLevel,
                                     final String testClassName,
                                     final int testTimeout,
                                     final J2clMavenMiddleware middleware,
                                     final int threadPoolSize,
                                     final MavenLogger logger) {
        super(
                cache,
                target,
                scope,
                classpathRequired,
                ignoredDependencies,
                javascriptSourceRequired,
                level,
                defines,
                externs,
                formatting,
                javaCompilerArguments,
                languageOut,
                sourceMaps,
                middleware,
                threadPoolSize,
                logger
        );
        this.browsers = browsers;
        this.browserLogLevel = browserLogLevel;
        this.testClassName = testClassName;
        this.testTimeout = testTimeout;
    }

    @Override
    public J2clSourcesKind sourcesKind() {
        return J2clSourcesKind.TEST;
    }

    @Override
    public List<String> entryPoints() {
        // this is the mangled name of a javascript file produced by the junit annotation-processor.
        return Lists.of("javatests." + this.testClassName + "_AdapterSuite");
    }

    @Override
    public J2clPath initialScriptFilename() {
        return this.project.directory()
                .append(this.directoryName(J2clStep.CLOSURE_COMPILE))
                .output()
                .append(this.testClassName + ".js");
    }

    @Override
    public HashBuilder computeHash(final Set<String> hashItemNames) {
        final HashBuilder hash = this.computeHash0(hashItemNames);

        // no need to include browser or testTimeout in hash as these do no affect generated js
        hashItemNames.add("test-classname: " + this.testClassName);
        hash.append(this.testClassName);

        return hash;
    }

    J2clMojoTestMavenContext setProject(final J2clDependency project) {
        this.project = project;

        return this;
    }

    private J2clDependency project;

    // steps............................................................................................................

    @Override
    List<J2clStep> steps() {
        return STEPS;
    }

    private final List<J2clStep> STEPS = Lists.of(
            J2clStep.HASH,
            J2clStep.UNPACK,
            J2clStep.JAVAC_COMPILE,
            J2clStep.GWT_INCOMPATIBLE_STRIP_JAVA_SOURCE,
            J2clStep.JAVAC_COMPILE_GWT_INCOMPATIBLE_STRIPPED_JAVA_SOURCE,
            J2clStep.SHADE_JAVA_SOURCE,
            J2clStep.SHADE_CLASS_FILES,
            J2clStep.TRANSPILE_JAVA_TO_JAVASCRIPT,
            J2clStep.CLOSURE_COMPILE,
            J2clStep.JUNIT_TESTS
    );

    // J2clMavenContext.................................................................................................

    @Override
    boolean shouldSkipSubmittingDependencyJobs() {
        return false;
    }

    // test only props..................................................................................................

    public List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers() {
        return this.browsers;
    }

    private final List<J2clStepWorkerWebDriverUnitTestRunnerBrowser> browsers;

    public BrowserLogLevel browserLogLevel() {
        return this.browserLogLevel;
    }

    private final BrowserLogLevel browserLogLevel;

    private final String testClassName;

    public int testTimeout() {
        return this.testTimeout;
    }

    int testTimeout;
}
