name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      - name: Maven dependency/resolve
        run: mvn dependency:resolve

      - name: Maven install
        run: mvn install -Dmaven.javadoc.skip=true -B -V -e > maven-install-output.txt

      - name: Print logs
        if: ${{ always() }}
        run: |
          tail -n 500 maven-install-output.txt
          tail -n 500 target/it-tests/junit-test/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: maven-install-output.txt
          path: maven-install-output.txt

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/formatting-pretty-print/build.log
          path: target/it/formatting-pretty-print/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/gwt-timer-j2cl-tests/build.log
          path: target/it/gwt-timer-j2cl-tests/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/gwt-timer-j2cl-tests-several/build.log
          path: target/it/gwt-timer-j2cl-tests-several/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/hello-world-reactor/build.log
          path: target/it/hello-world-reactor/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/ignored-files/build.log
          path: target/it/ignored-files/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test/build.log
          path: target/it/junit-test/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-custom-source-dir/build.log
          path: target/it/junit-test-custom-source-dir/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-dependency-graph/build.log
          path: target/it/junit-test-dependency-graph/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-dependency-gwt-incompatible/build.log
          path: target/it/junit-test-dependency-gwt-incompatible/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-jre-class-replaced-shaded/build.log
          path: target/it/junit-test-jre-class-replaced-shaded/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-jre-class-replaced-shaded2/build.log
          path: target/it/junit-test-jre-class-replaced-shaded2/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-jre-class-replaced-shaded3/build.log
          path: target/it/junit-test-jre-class-replaced-shaded3/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-jre-class-replaced-shaded4/build.log
          path: target/it/junit-test-jre-class-replaced-shaded4/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-jre-class-shaded/build.log
          path: target/it/junit-test-jre-class-shaded/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-pom-classpath-required/build.log
          path: target/it/junit-test-pom-classpath-required/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-pom-ignored-dependencies/build.log
          path: target/it/junit-test-pom-ignored-dependencies/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-pom-ignored-dependencies2/build.log
          path: target/it/junit-test-pom-ignored-dependencies2/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/junit-test-pom-javascript-source-required/build.log
          path: target/it/junit-test-pom-javascript-source-required/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/language-out-es5/build.log
          path: target/it/language-out-es5/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/shade/build.log
          path: target/it/shade/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/super-source/build.log
          path: target/it/super-source/build.log

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: it/vertispan-connected/build.log
          path: target/it/vertispan-connected/build.log

